---
- name: Setup for install
  hosts: all
  remote_user: ec2-user
  become: yes
  
  tasks:
  - name: Install apache http server packages 
    yum:
      name: httpd
      state: present

  - name: ensure apache http server is running
    service:
      name: httpd 
      state: started